### ISSUE TITLE
Mod loading error

### ISSUE THREAD

**Issue by lebanni** [Unixkitty/timecontrol#1]
Versions :
Minecraft 1.16.3
forge-1.16.3-34.1.12.jar
timecontrol-1.16.1-1.1.0.0.jar

Server crashed at start.

[crash-2020-10-08_12.15.26-fml.txt](https://github.com/Unixkitty/timecontrol/files/5347140/crash-2020-10-08_12.15.26-fml.txt)

**Comment by Unixkitty** [comment]
Seems like something changed in rule registration for server worlds between 1.15 and 1.16
