### ISSUE TITLE
Time Control not changing the day length

### ISSUE THREAD

**Issue by BadNerdCreating** [Unixkitty/timecontrol#10]
I turned off the doDaylightCycle and changed it to false. I set the daylight to 20 min and kept nighttime at 10 min and restarted the server and my game. However it hasn't changed the time. I timed it and a day cycle is still 10 minutes. I'm not sure what else I need to do. 

Thank you for your help

**Comment by Unixkitty** [comment]
Try to start with a fresh config, the vanilla gamerule will be set to false by the mod when restarting the server.
Check if the /timecontrol command is available in-game, that will be an easy check for whether the mod is properly installed.
