### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [Unixkitty/timecontrol#11]
Is there a discord server for this mod?

**Comment by Unixkitty** [comment]
Is there need for one?

**Comment by Fireworkstars46** [comment]
I think it would be more effective and better cause GitHub I have to manually refresh the page each time I get a reply (annoying) and discord gets better notifications etc

**Comment by Unixkitty** [comment]
Well, okay, I honestly don't think my mods are popular enough, but I started working on a server to host so that people that have questions have a more convenient place for it: https://discord.gg/sKwS3c62uM
