### ISSUE TITLE
Port-Request: 1.20.1 Compatibility

### ISSUE THREAD

**Issue by Tursiops-G** [Unixkitty/timecontrol#12]
A port to 1.20.1 would be wonderful. :)

**Comment by Unixkitty** [comment]
There's a 1.20.1 already? Wow, time to start looking into it!

**Comment by Unixkitty** [comment]
Done, let me know if you encounter any issues as it'll be a long time before I play 1.20+ myself!

**Comment by Tursiops-G** [comment]
Works like a charm... Thanks! :)
