### ISSUE TITLE
Day Cycle has Stopped completely

### ISSUE THREAD

**Issue by JasonBean-99** [Unixkitty/timecontrol#15]
I removed the mod and now my world is frozen in time, I deleted all configs in my save too but nothing.

**Comment by JasonBean-99** [comment]
Managed to fix the issue, when removing the mod it auto sets the daylight cycle game rule to false

**Comment by Unixkitty** [comment]
This is noted in the mod description:
![cw18hoMcYCSl](https://github.com/Unixkitty/timecontrol/assets/33952539/f85f98f4-7232-4537-ab05-483dd07e59fb)
