### ISSUE TITLE
Port-Request: 1.20.4 Compatibility

### ISSUE THREAD

**Issue by GrosiekPL** [Unixkitty/timecontrol#18]
Any plans if it's not too troubling to update the mod to 1.20.4?

**Comment by athiccsadist** [comment]
same here

**Comment by Unixkitty** [comment]
Fabric version should be out for 1.20.4 sometime this week

**Comment by Unixkitty** [comment]
Fixed Fabric 1.20.4 compatibility since 2f45495b5dfc9d8a5cef290c44e912e99c9645fe and release should be up.
