### ISSUE TITLE
Sky Stutter

### ISSUE THREAD

**Issue by Gata-chan** [Unixkitty/timecontrol#19]
I used this mod for a modpack that uses TerraFirmaCraft.

After changing day/night lenghts and then using [/time set] command the sky started to stutter and the sun jumping between positions every second or so...

Does [/time set] break this mod or is there something in TerraFirmaCraft that breaks it? I wouldn't know, and I have no clue how to check

**Comment by Unixkitty** [comment]
I can say with certainty that what you're describing is abnormal behaviour and usually indicates desync between client and server.
Vanilla /time command should work normally with my mod.

TFC is quite an invasive and expansive mod - it seems that they override the vanilla time command with their own implementation: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.20.x/src/main/java/net/dries007/tfc/common/commands/TimeCommand.java

**Comment by Gata-chan** [comment]
Oh damn, how upsetting, I just wanted longer daytime but it seems that it's not possible to achive combining your mod with TF C(or any timescale mod with TFC, for that matter)

bummer
