### ISSUE TITLE
Time stop

### ISSUE THREAD

**Issue by solbolt2** [Unixkitty/timecontrol#6]
Hey there!

I'm trying to have longer days and also stop time when everyone logs out of the server.

I've been trying to find a combination of mods that work together.
I've tried "longer days"
I've tried "Extended days"

with "Time Shall Not Pass"

I guess the way they handle the ticks ends up making time go backward when I used those together.
It seems to do the same when I use your mod with the "Time shall not pass" mod unless I change the system time or toy with it.
Either way

If you could somehow implement the time-stopping feature of "Time Shall Not Pass"  Into your mod it would be perfect!
Or even add some kind of compatibility with it that would be amazing! 

I just want to make days longer and be able to freeze time when all players log out. Is that too much to ask for? lol

Just thought I would reach out to see what you thought.
Your mod is awesome by the way!

Thank you so much!
-Solbolt

**Comment by Unixkitty** [comment]
Hello there!

Thank you for the kind word.

My mod watches for the gamerule 'doDaylightCycle_tc' to see if it needs to advance time, which it does by it's own calculations.

At the moment your real option is to find a way to toggle the gamerule if you really want to stop the time advancing when nobody's online. Other than that, I might add this as an option at some point. What mc version are you on?

**Comment by solbolt2** [comment]
Hey!

Okay, that clears it up then. It's definitely a cleaner way to set that up.

Then I suppose the other mod does some kind of subtraction of time so when
"doDaylightCycle_tc"   is turned off it rewinds time. I see I see.
I used to set something up with a command block clock that would progress
time slowly with the gamerule turned off. So that makes sense now.
I suppose I could set up a Redstone/command clock that checks for players
online and only adds time when it detects players and keep the gamerule off.

Having an option to slow time down along with this mod would be very
helpful and more efficient since it's already watching for players to come
on or offline.
I'm not sure how TimeControl
<https://www.curseforge.com/minecraft/mc-mods/time-control> did it but it
seemed to be fairly robust whereas "longer days" seems to just subtract a
fraction of ticks. (Your answer cleared that up.) Thanks for the response!

I'm on 1.12.2 because of Rl Craft. The days feel too short, so on this
server with a couple of friends, I like the days a bit longer.
This is also why I wanted to stop time so that we don't wake up in other
seasons/nighttime/daytime and also run up the days? Etc.
Though serene does offer a config option to stop seasons when no one is
online, not for days howver.


Thank you very much for taking the time to respond!
It helped me out a lot!

-Sol
