### ISSUE TITLE
Time stops completely when daylength is set to > 200 minutes

### ISSUE THREAD

**Issue by EBrarian** [Unixkitty/timecontrol#9]
As it says in the title : the mod works but as soon as the day length is set to greater than 200 minutes, time stops completely.

Tested on : 
Minecraft version 1.19,2
Forge version 43.2.8
No other mods than timecontrol
gamerule doDaylightCycle set to false
gamerule doDaylightCycle_tc set to true

I tried setting '	sync_to_system_time_rate' to 10 to see if that helps but it did not.

**Comment by Unixkitty** [comment]
Thanks for reporting! I will look into this.

**Comment by Unixkitty** [comment]
Sorry this took so long, should be fixed with https://github.com/Unixkitty/timecontrol/commit/3bbc813e872ad351d50163a6b6b7401baf3a73d5 version 1.1.3.1
